---
- name: Configure global macOS defaults
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ macos_defaults_global }}"

- name: Configure Finder defaults
  community.general.osx_defaults:
    domain: com.apple.finder
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ macos_defaults_finder }}"
  notify: Restart Finder

- name: Configure Dock defaults
  community.general.osx_defaults:
    domain: com.apple.dock
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ macos_defaults_dock }}"
  notify: Restart Dock
