---
- name: Set Homebrew prefix
  ansible.builtin.set_fact:
    homebrew_prefix: "{{ '/opt/homebrew' if ansible_facts.architecture == 'arm64' else '/usr/local' }}"
    homebrew_formulae_packages: "{{ homebrew_formulae.values() | flatten }}"
    homebrew_cask_packages: "{{ homebrew_casks.values() | flatten }}"
    homebrew_environment:
      PATH: "{{ homebrew_prefix }}/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
      HOMEBREW_NO_AUTO_UPDATE: '1'

- name: Check whether Homebrew is installed
  ansible.builtin.stat:
    path: "{{ homebrew_prefix }}/bin/brew"
  register: homebrew_binary

- name: Install Homebrew
  ansible.builtin.shell: |
    set -euo pipefail
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    executable: /bin/bash
  changed_when: true
  when: not homebrew_binary.stat.exists

- name: Install Homebrew taps
  community.general.homebrew_tap:
    name: "{{ homebrew_taps }}"
    state: present
  environment: "{{ homebrew_environment }}"

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ homebrew_formulae_packages }}"
    state: present
    update_homebrew: true
  environment: "{{ homebrew_environment }}"

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
    accept_external_apps: true
  environment: "{{ homebrew_environment }}"
