---
homebrew_taps:
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/services

homebrew_formulae:
  cli:
    - aspell
    - cbonsai
    - eza
    - fx
    - fzf
    - gh
    - git
    - glow
    - gnu-typist
    - gum
    - jq
    - nnn
    - ripgrep
    - starship
    - thefuck
    - tmux
    - tty-clock
    - wget
    - xplr
    - yazi
    - zellij
    - zoxide
  cloud_devops:
    - act
    - ansible
    - aws-sam-cli
    - awscli
    - dependabot
    - helm
    - lazydocker
    - lazygit
    - scorecard
    - tflint
    - tfsec
    - trivy
    - trufflehog
  runtimes:
    - go
    - gopls
    - node
    - nvm
    - pyenv
    - python@3.12
    - python-lsp-server
    - rustup
    - ty
    - typescript-language-server
  editors:
    - helix
    - neovim
  security:
    - gnupg
    - pinentry-mac
    - restic
  tooling:
    - cocoapods
    - llvm
    - plantuml
    - watchman

homebrew_casks:
  development:
    - aws-vault
    - aws-vault-binary
    - chromedriver
    - docker
    - docker-desktop
    - flutter
    - github
    - insomnia
    - jetbrains-toolbox
    - visual-studio-code
  productivity:
    - alfred
    - alt-tab
    - flycut
    - obsidian
    - rectangle
    - raycast
    - trilium-notes
    - wallspace
  terminal:
    - iterm2
    - termius
  browsers:
    - google-chrome
  design:
    - affinity
    - blender
    - krita
  media:
    - calibre
    - obs
    - vlc
  remote_access:
    - amazon-workspaces
    - aws-vpn-client
    - tunnelblick
  documentation:
    - mactex
  virtualization:
    - utm
    - vagrant
  fonts:
    - font-hack-nerd-font
