---
homebrew_taps:
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/services

homebrew_formulae:
  cli:
    - aspell
    - cbonsai
    - eza
    - fx
    - fzf
    - gh
    - git
    - glow
    - gnu-typist
    - gum
    - jq
    - mas
    - nnn
    - ripgrep
    - starship
    - thefuck
    - tmux
    - tty-clock
    - wget
    - xplr
    - yazi
    - zellij
    - zoxide
  cloud_devops:
    - act
    - ansible
    - aws-sam-cli
    - awscli
    - dependabot
    - helm
    - lazydocker
    - lazygit
    - scorecard
    - tflint
    - tfsec
    - trivy
    - trufflehog
  runtimes:
    - go
    - gopls
    - node
    - nvm
    - pyenv
    - python@3.12
    - python-lsp-server
    - rustup
    - ty
    - typescript-language-server
  editors:
    - helix
    - neovim
  security:
    - gnupg
    - pinentry-mac
  tooling:
    - cocoapods
    - llvm
    - plantuml
    - watchman

homebrew_casks:
  development:
    - docker
    - visual-studio-code
  productivity:
    - raycast
  terminal:
    - iterm2
  fonts:
    - font-hack-nerd-font

homebrew_mas_apps: []
# Example:
# homebrew_mas_apps:
#   - id: 497799835
#     name: Xcode
